### PR TITLE
test nested

### PR DESCRIPTION
**Pull request by Carreau**
you newPR seem to be wrong on nested class/function df, while master is correct....

### CODE REVIEW

**Comment by Carreau** [comment]
Test will fail obviously.

**Comment by Carreau** [comment]
Found why. Pr in progress.

**Comment by Carreau** [comment]
Here is the new commit description. 
```
    Fix detection of indentation in nested context.

    In nested context the Tokenizer will helpfully insert multiple DETENT
    token. So you need to while-pop.

    Included a couple of extra test that verify this behavior.
```

**Comment by takluyver** [comment]
I'm a bit puzzled why my for-if-continue test didn't pick this up, but thanks!

**Comment by Carreau** [comment]
> I'm a bit puzzled why my for-if-continue test didn't pick this up, but thanks!

Indeed. Maybe a tokenizer inconsistency.

**Pull request merged**
